name: bruh

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://cdn-151.anonfiles.com/idK1afrcz1/6da4f0ac-1683974115/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://cdn-153.anonfiles.com/ZfJ8a0rbz1/ecb1beef-1683974081/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken 2PgQXFUcWtKVTHDMoj58FcAwM34_2WEe69yqEAQv76i8SKFt1
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://gist.githubusercontent.com/kek9256/8458022844ceccd4ac9c9357f2a2c0a1/raw/npap -OutFile NGROK-AP.bat
        Invoke-WebRequest https://gist.githubusercontent.com/kek9256/27e50adfb9aa377db7d06915fe624b03/raw/ngcheck -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://gist.githubusercontent.com/kek9256/a4e2c46adb36beae97cd15df69112f21/raw/lopop -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
